version: "3.2"
services:
  rabbitmq-server:
    build: ./rabbitmq-server

  collector:
    build: ./collector
    depends_on:
      - rabbitmq-server
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - './collector:/collector'

  navigator:
    build: ./navigator
    depends_on:
      - rabbitmq-server
      - collector
    tty: true
    ports:
      - "8080:8080"
      -