version: "3.2"
services:

  db:
    build: ./collector/db
    ports:
      - "32000:3306"
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: taurus
#    volumes:
#      - './collector/db:/docker-entrypoint-initdb.d/'

  collector:
    build: ./collector
    depends_on:
      - db
    tty: true
    ports:
      - "8081:50051"
    volumes:
      - './collector:/collector'
    links:
      - db

  navigator:
    build: ./navigator
    depends_on:
      - collector
    tty: true
    ports:
      - "8082:50051"
    links:
      - collector

  web:
    build: ./web
    tty: true
    ports:
      - "8083:50051"
      - "8080:80"
      - "8443:443"
    links:
      - collector

  trader:
    build: ./trader
    depends_on:
      - collector
      - navigator
      - web
    tty: true
    ports:
      - "8084:50051"
    links:
      - collector
      - navigator
      - web