version: "3.2"
services:

  db:
    image: mysql:8.0
    dns:
      - 8.8.8.8
    ports:
      - "32000:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/

  collector:
    build: ./collector
    depends_on:
      - db
    tty: true
    ports:
      - "8081:50051"
    volumes:
      - './collector:/collector'

  navigator:
    build: ./navigator
    depends_on:
      - collector
    tty: true
    ports:
      - "8082:50051"

  web:
    build: ./web
    tty: true
    ports:
      - "8083:50051"
      - "8080:80"
      - "8443:443"

  trader:
    build: ./trader
    depends_on:
      - collector
      - navigator
      - web
    tty: true
    ports:
      - "8084:50051"