# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PATH/candlestick.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PATH/candlestick.proto',
  package='taurus',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x16PATH/candlestick.proto\x12\x06taurus\"x\n\x0b\x43\x61ndlestick\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x0c\n\x04open\x18\x02 \x01(\x01\x12\x0c\n\x04high\x18\x03 \x01(\x01\x12\x0b\n\x03low\x18\x04 \x01(\x01\x12\r\n\x05\x63lose\x18\x05 \x01(\x01\x12\x0e\n\x06volume\x18\x06 \x01(\x01\x12\x0e\n\x06symbol\x18\x07 \x01(\t\";\n\x0e\x43\x61ndlestickSet\x12)\n\x0c\x63\x61ndlesticks\x18\x01 \x03(\x0b\x32\x13.taurus.Candlestickb\x06proto3')
)




_CANDLESTICK = _descriptor.Descriptor(
  name='Candlestick',
  full_name='taurus.Candlestick',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='taurus.Candlestick.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='open', full_name='taurus.Candlestick.open', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='high', full_name='taurus.Candlestick.high', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='low', full_name='taurus.Candlestick.low', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='close', full_name='taurus.Candlestick.close', index=4,
      number=5, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='volume', full_name='taurus.Candlestick.volume', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='symbol', full_name='taurus.Candlestick.symbol', index=6,
      number=7, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=154,
)


_CANDLESTICKSET = _descriptor.Descriptor(
  name='CandlestickSet',
  full_name='taurus.CandlestickSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='candlesticks', full_name='taurus.CandlestickSet.candlesticks', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=215,
)

_CANDLESTICKSET.fields_by_name['candlesticks'].message_type = _CANDLESTICK
DESCRIPTOR.message_types_by_name['Candlestick'] = _CANDLESTICK
DESCRIPTOR.message_types_by_name['CandlestickSet'] = _CANDLESTICKSET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Candlestick = _reflection.GeneratedProtocolMessageType('Candlestick', (_message.Message,), {
  'DESCRIPTOR' : _CANDLESTICK,
  '__module__' : 'PATH.candlestick_pb2'
  # @@protoc_insertion_point(class_scope:taurus.Candlestick)
  })
_sym_db.RegisterMessage(Candlestick)

CandlestickSet = _reflection.GeneratedProtocolMessageType('CandlestickSet', (_message.Message,), {
  'DESCRIPTOR' : _CANDLESTICKSET,
  '__module__' : 'PATH.candlestick_pb2'
  # @@protoc_insertion_point(class_scope:taurus.CandlestickSet)
  })
_sym_db.RegisterMessage(CandlestickSet)


# @@protoc_insertion_point(module_scope)
