# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import collector_pb2 as collector__pb2
import trader_pb2 as trader__pb2


class TraderStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetRecentTrades = channel.unary_unary(
        '/taurus.Trader/GetRecentTrades',
        request_serializer=collector__pb2.TradeRequest.SerializeToString,
        response_deserializer=collector__pb2.TradeSet.FromString,
        )
    self.SetConstraint = channel.unary_unary(
        '/taurus.Trader/SetConstraint',
        request_serializer=trader__pb2.Constraint.SerializeToString,
        response_deserializer=trader__pb2.ConstraintReply.FromString,
        )
    self.MakeTrade = channel.unary_unary(
        '/taurus.Trader/MakeTrade',
        request_serializer=collector__pb2.Trade.SerializeToString,
        response_deserializer=trader__pb2.TradeReply.FromString,
        )


class TraderServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetRecentTrades(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetConstraint(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def MakeTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TraderServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetRecentTrades': grpc.unary_unary_rpc_method_handler(
          servicer.GetRecentTrades,
          request_deserializer=collector__pb2.TradeRequest.FromString,
          response_serializer=collector__pb2.TradeSet.SerializeToString,
      ),
      'SetConstraint': grpc.unary_unary_rpc_method_handler(
          servicer.SetConstraint,
          request_deserializer=trader__pb2.Constraint.FromString,
          response_serializer=trader__pb2.ConstraintReply.SerializeToString,
      ),
      'MakeTrade': grpc.unary_unary_rpc_method_handler(
          servicer.MakeTrade,
          request_deserializer=collector__pb2.Trade.FromString,
          response_serializer=trader__pb2.TradeReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'taurus.Trader', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
