# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: trader.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import collector_pb2 as collector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='trader.proto',
  package='taurus',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ctrader.proto\x12\x06taurus\x1a\x0f\x63ollector.proto\"\x1a\n\nConstraint\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t\"!\n\x0f\x43onstraintReply\x12\x0e\n\x06status\x18\x01 \x01(\t\"\x1c\n\nTradeReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xb7\x01\n\x06Trader\x12;\n\x0fGetRecentTrades\x12\x14.taurus.TradeRequest\x1a\x10.taurus.TradeSet\"\x00\x12>\n\rSetConstraint\x12\x12.taurus.Constraint\x1a\x17.taurus.ConstraintReply\"\x00\x12\x30\n\tMakeTrade\x12\r.taurus.Trade\x1a\x12.taurus.TradeReply\"\x00\x62\x06proto3')
  ,
  dependencies=[collector__pb2.DESCRIPTOR,])




_CONSTRAINT = _descriptor.Descriptor(
  name='Constraint',
  full_name='taurus.Constraint',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='taurus.Constraint.data', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=67,
)


_CONSTRAINTREPLY = _descriptor.Descriptor(
  name='ConstraintReply',
  full_name='taurus.ConstraintReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='taurus.ConstraintReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=102,
)


_TRADEREPLY = _descriptor.Descriptor(
  name='TradeReply',
  full_name='taurus.TradeReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='taurus.TradeReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['Constraint'] = _CONSTRAINT
DESCRIPTOR.message_types_by_name['ConstraintReply'] = _CONSTRAINTREPLY
DESCRIPTOR.message_types_by_name['TradeReply'] = _TRADEREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Constraint = _reflection.GeneratedProtocolMessageType('Constraint', (_message.Message,), {
  'DESCRIPTOR' : _CONSTRAINT,
  '__module__' : 'trader_pb2'
  # @@protoc_insertion_point(class_scope:taurus.Constraint)
  })
_sym_db.RegisterMessage(Constraint)

ConstraintReply = _reflection.GeneratedProtocolMessageType('ConstraintReply', (_message.Message,), {
  'DESCRIPTOR' : _CONSTRAINTREPLY,
  '__module__' : 'trader_pb2'
  # @@protoc_insertion_point(class_scope:taurus.ConstraintReply)
  })
_sym_db.RegisterMessage(ConstraintReply)

TradeReply = _reflection.GeneratedProtocolMessageType('TradeReply', (_message.Message,), {
  'DESCRIPTOR' : _TRADEREPLY,
  '__module__' : 'trader_pb2'
  # @@protoc_insertion_point(class_scope:taurus.TradeReply)
  })
_sym_db.RegisterMessage(TradeReply)



_TRADER = _descriptor.ServiceDescriptor(
  name='Trader',
  full_name='taurus.Trader',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=135,
  serialized_end=318,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetRecentTrades',
    full_name='taurus.Trader.GetRecentTrades',
    index=0,
    containing_service=None,
    input_type=collector__pb2._TRADEREQUEST,
    output_type=collector__pb2._TRADESET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SetConstraint',
    full_name='taurus.Trader.SetConstraint',
    index=1,
    containing_service=None,
    input_type=_CONSTRAINT,
    output_type=_CONSTRAINTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='MakeTrade',
    full_name='taurus.Trader.MakeTrade',
    index=2,
    containing_service=None,
    input_type=collector__pb2._TRADE,
    output_type=_TRADEREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRADER)

DESCRIPTOR.services_by_name['Trader'] = _TRADER

# @@protoc_insertion_point(module_scope)
