# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import collector_pb2 as collector__pb2
import navigator_pb2 as navigator__pb2
import web_pb2 as web__pb2


class NavigatorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.PutCandlesticks = channel.unary_unary(
        '/taurus.Navigator/PutCandlesticks',
        request_serializer=collector__pb2.CandlestickSet.SerializeToString,
        response_deserializer=navigator__pb2.CandlestickReply.FromString,
        )
    self.InformPortfolio = channel.unary_unary(
        '/taurus.Navigator/InformPortfolio',
        request_serializer=navigator__pb2.Portfolio.SerializeToString,
        response_deserializer=web__pb2.InformReply.FromString,
        )


class NavigatorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def PutCandlesticks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InformPortfolio(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NavigatorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'PutCandlesticks': grpc.unary_unary_rpc_method_handler(
          servicer.PutCandlesticks,
          request_deserializer=collector__pb2.CandlestickSet.FromString,
          response_serializer=navigator__pb2.CandlestickReply.SerializeToString,
      ),
      'InformPortfolio': grpc.unary_unary_rpc_method_handler(
          servicer.InformPortfolio,
          request_deserializer=navigator__pb2.Portfolio.FromString,
          response_serializer=web__pb2.InformReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'taurus.Navigator', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
