# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import collector_pb2 as collector__pb2
import web_pb2 as web__pb2


class WebStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetConstraints = channel.unary_unary(
        '/taurus.Web/GetConstraints',
        request_serializer=web__pb2.ConstraintRequest.SerializeToString,
        response_deserializer=web__pb2.ConstraintSet.FromString,
        )
    self.InformTrade = channel.unary_unary(
        '/taurus.Web/InformTrade',
        request_serializer=collector__pb2.Trade.SerializeToString,
        response_deserializer=web__pb2.InformReply.FromString,
        )
    self.InformCandlesticks = channel.unary_unary(
        '/taurus.Web/InformCandlesticks',
        request_serializer=collector__pb2.CandlestickSet.SerializeToString,
        response_deserializer=web__pb2.InformReply.FromString,
        )


class WebServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetConstraints(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InformTrade(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def InformCandlesticks(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_WebServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetConstraints': grpc.unary_unary_rpc_method_handler(
          servicer.GetConstraints,
          request_deserializer=web__pb2.ConstraintRequest.FromString,
          response_serializer=web__pb2.ConstraintSet.SerializeToString,
      ),
      'InformTrade': grpc.unary_unary_rpc_method_handler(
          servicer.InformTrade,
          request_deserializer=collector__pb2.Trade.FromString,
          response_serializer=web__pb2.InformReply.SerializeToString,
      ),
      'InformCandlesticks': grpc.unary_unary_rpc_method_handler(
          servicer.InformCandlesticks,
          request_deserializer=collector__pb2.CandlestickSet.FromString,
          response_serializer=web__pb2.InformReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'taurus.Web', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
