# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: web.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import trader_pb2 as trader__pb2
import collector_pb2 as collector__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='web.proto',
  package='taurus',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\tweb.proto\x12\x06taurus\x1a\x0ctrader.proto\x1a\x0f\x63ollector.proto\"$\n\x11\x43onstraintRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\"7\n\rConstraintSet\x12&\n\nconstraint\x18\x01 \x03(\x0b\x32\x12.taurus.Constraint\"\x1d\n\x0bInformReply\x12\x0e\n\x06status\x18\x01 \x01(\t2\xc5\x01\n\x03Web\x12\x44\n\x0eGetConstraints\x12\x19.taurus.ConstraintRequest\x1a\x15.taurus.ConstraintSet\"\x00\x12\x33\n\x0bInformTrade\x12\r.taurus.Trade\x1a\x13.taurus.InformReply\"\x00\x12\x43\n\x12InformCandlesticks\x12\x16.taurus.CandlestickSet\x1a\x13.taurus.InformReply\"\x00\x62\x06proto3')
  ,
  dependencies=[trader__pb2.DESCRIPTOR,collector__pb2.DESCRIPTOR,])




_CONSTRAINTREQUEST = _descriptor.Descriptor(
  name='ConstraintRequest',
  full_name='taurus.ConstraintRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='taurus.ConstraintRequest.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=52,
  serialized_end=88,
)


_CONSTRAINTSET = _descriptor.Descriptor(
  name='ConstraintSet',
  full_name='taurus.ConstraintSet',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='constraint', full_name='taurus.ConstraintSet.constraint', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=145,
)


_INFORMREPLY = _descriptor.Descriptor(
  name='InformReply',
  full_name='taurus.InformReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='taurus.InformReply.status', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=176,
)

_CONSTRAINTSET.fields_by_name['constraint'].message_type = trader__pb2._CONSTRAINT
DESCRIPTOR.message_types_by_name['ConstraintRequest'] = _CONSTRAINTREQUEST
DESCRIPTOR.message_types_by_name['ConstraintSet'] = _CONSTRAINTSET
DESCRIPTOR.message_types_by_name['InformReply'] = _INFORMREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConstraintRequest = _reflection.GeneratedProtocolMessageType('ConstraintRequest', (_message.Message,), dict(
  DESCRIPTOR = _CONSTRAINTREQUEST,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:taurus.ConstraintRequest)
  ))
_sym_db.RegisterMessage(ConstraintRequest)

ConstraintSet = _reflection.GeneratedProtocolMessageType('ConstraintSet', (_message.Message,), dict(
  DESCRIPTOR = _CONSTRAINTSET,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:taurus.ConstraintSet)
  ))
_sym_db.RegisterMessage(ConstraintSet)

InformReply = _reflection.GeneratedProtocolMessageType('InformReply', (_message.Message,), dict(
  DESCRIPTOR = _INFORMREPLY,
  __module__ = 'web_pb2'
  # @@protoc_insertion_point(class_scope:taurus.InformReply)
  ))
_sym_db.RegisterMessage(InformReply)



_WEB = _descriptor.ServiceDescriptor(
  name='Web',
  full_name='taurus.Web',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=179,
  serialized_end=376,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetConstraints',
    full_name='taurus.Web.GetConstraints',
    index=0,
    containing_service=None,
    input_type=_CONSTRAINTREQUEST,
    output_type=_CONSTRAINTSET,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InformTrade',
    full_name='taurus.Web.InformTrade',
    index=1,
    containing_service=None,
    input_type=collector__pb2._TRADE,
    output_type=_INFORMREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='InformCandlesticks',
    full_name='taurus.Web.InformCandlesticks',
    index=2,
    containing_service=None,
    input_type=collector__pb2._CANDLESTICKSET,
    output_type=_INFORMREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEB)

DESCRIPTOR.services_by_name['Web'] = _WEB

# @@protoc_insertion_point(module_scope)
